# -*- coding: utf-8 -*-
"""DSA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hxIxABVk6dCHDoAfg63ycWd1O23kfJbO

Two Sum
"""

def two_sum(nums, target):
    seen = {}

    for i, num in enumerate(nums):
        complement = target - num

        if complement in seen:
            return [seen[complement], i]

        seen[num] = i

    return []

print(two_sum([2, 7, 11, 15], 9))

"""Longest Substring"""

def longest_substring(s):
    seen = set()
    left = 0
    max_length = 0

    for right in range(len(s)):
        while s[right] in seen:
            seen.remove(s[left])
            left += 1

        seen.add(s[right])
        max_length = max(max_length, right - left + 1)

    return max_length

print(longest_substring("abcabcbb"))

"""Maximum Subarray Sum"""

def max_subarray(nums):
    current = nums[0]
    maximum = nums[0]

    for i in range(1, len(nums)):
        current = max(nums[i], current + nums[i])
        maximum = max(maximum, current)

    return maximum

print(max_subarray([-2,1,-3,4,-1,2,1,-5,4]))

"""Merge Overlapping Intervals"""

def merge_intervals(intervals):
    intervals.sort()

    merged = []

    for start, end in intervals:
        if not merged or start > merged[-1][1]:
            merged.append([start, end])
        else:
            merged[-1][1] = max(merged[-1][1], end)

    return merged

print(merge_intervals([[1,3],[2,6],[8,10],[9,12]]))

"""Valid Parentheses"""

def valid_parentheses(s):
    stack = []

    pairs = {
        ')': '(',
        ']': '[',
        '}': '{'
    }

    for char in s:
        if char in '([{':
            stack.append(char)

        else:
            if not stack or stack[-1] != pairs[char]:
                return False

            stack.pop()

    return len(stack) == 0

print(valid_parentheses("({[]})"))

"""Longest Consecutive Sequence"""

def longest_consecutive(nums):
    numbers = set(nums)
    longest = 0

    for num in numbers:

        if num - 1 not in numbers:
            current = num
            length = 1

            while current + 1 in numbers:
                current += 1
                length += 1

            longest = max(longest, length)

    return longest


print(longest_consecutive([100,4,200,1,3,2]))

"""No.Of Islands"""

def num_islands(grid):
    rows = len(grid)
    cols = len(grid[0])
    count = 0

    def dfs(r, c):
        if r < 0 or r >= rows or c < 0 or c >= cols:
            return

        if grid[r][c] == '0':
            return

        grid[r][c] = '0'

        dfs(r + 1, c)
        dfs(r - 1, c)
        dfs(r, c + 1)
        dfs(r, c - 1)

    for r in range(rows):
        for c in range(cols):
            if grid[r][c] == '1':
                count += 1
                dfs(r, c)

    return count

"""Cycle in Linked List"""

class Node:
    def __init__(self, val):
        self.val = val
        self.next = None

def has_cycle(head):
    slow = fast = head
    while fast and fast.next:
        slow = slow.next
        fast = fast.next.next
        if slow == fast:
            return True
    return False

# Input: 1 -> 2 -> 3 -> back to 2
a, b, c = Node(1), Node(2), Node(3)
a.next = b
b.next = c
c.next = b          # cycle

print(has_cycle(a))  # True

"""Level Order Traversal (BFS)"""

from collections import deque

class Node:
    def __init__(self, val):
        self.val = val
        self.left = None
        self.right = None

def level_order(root):
    if not root:
        return []
    result = []
    queue = deque([root])
    while queue:
        level = []
        for _ in range(len(queue)):     # one level at a time
            node = queue.popleft()
            level.append(node.val)
            if node.left:
                queue.append(node.left)
            if node.right:
                queue.append(node.right)
        result.append(level)
    return result
root = Node(3)
root.left = Node(9)
root.right = Node(20)
root.right.left = Node(15)
root.right.right = Node(7)

print(level_order(root))   # [[3], [9, 20], [15, 7]]

"""Lowest Common Ancestor"""

class Node:
    def __init__(self, val):
        self.val = val
        self.left = None
        self.right = None

def lca(root, p, q):
    if not root or root == p or root == q:
        return root
    left = lca(root.left, p, q)
    right = lca(root.right, p, q)
    if left and right:          # p and q on different sides
        return root
    return left or right


root = Node(3)
root.left = Node(5)
root.right = Node(1)
root.left.left = Node(6)
root.left.right = Node(2)
root.right.left = Node(0)
root.right.right = Node(8)
root.left.right.left = Node(7)
root.left.right.right = Node(4)

p = root.left            # node 5
q = root.right           # node 1
print(lca(root, p, q).val)   # 3

p = root.left            # node 5
q = root.left.right.right    # node 4
print(lca(root, p, q).val)   # 5